[cachyos-v3]
Server = https://mirror.cachyos.org/repo/x86_64_v3/$repo

[cachyos-core-v3]
Server = https://mirror.cachyos.org/repo/x86_64_v3/$repo

[cachyos-extra-v3]
Server = https://mirror.cachyos.org/repo/x86_64_v3/$repo
